spring.application.name=csd230-s26-lab6-firstname-lastname
# Default to H2 for easy local dev and cloud hosting
spring.profiles.active=${SPRING_PROFILES_ACTIVE:h2}

# Use the PORT provided by Render, or default to 8080 locally
server.port=${PORT:8080}

rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem