spring.application.name=csd230-s26-lecture-2.9-starter
server.port=8080

rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem

# Default to MySql if no profile is selected
# see appli cation-mysql.properties
#spring.profiles.active=h2
#spring.profiles.active=mysql
# Switch between "dev" (H2) and "mysql" (Docker) here:
spring.profiles.active=h2


