classDiagram
    direction RL
    class Clock {
        -time: Time
        +setTime(Time t)
    }


    class ClockDisplay {
        +updateView(Time t)
    }


    class DigitalDisplay {
        -fontSize: int
        +updateView(Time t)
    }


    class AnalogDisplay {
        -handColor: String
        +updateView(Time t)
    }


    <<interface>> ClockDisplay


    Clock *-- ClockDisplay : has 1
    ClockDisplay <|.. DigitalDisplay : implements
    ClockDisplay <|.. AnalogDisplay : implements